### ISSUE TITLE
add default config file under `~/.config/cumin/cumin.yaml`

### ISSUE THREAD

**Issue by concaf** [concaf/cumin#1]
```yaml
defaults:
  project: SRVKP
  labels:
  - "github-imported"
```
